### ISSUE TITLE
win64: Build failure

### ISSUE THREAD

**Issue by Trentonoliphant** [conda-archive/conda-ui#12]
```
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    build()
  File "setup.py", line 10, in build
    retcode = subprocess.call(["coffee", "--no-header", "-c", join("conda_ui", "static", "conda_ui")])
  File "C:\users\trenton\Anaconda\envs\_build________________________________________________
_________________________\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\users\trenton\Anaconda\envs\_build_______________________________________________
_________________________\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\users\trenton\Anaconda\envs\_build________________________________________________
_________________________\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
Command failed: C:\WINDOWS\system32\cmd.exe /c bld.bat
```

**Comment by asmeurer** [comment]
Try running `conda update conda-build`

**Comment by asmeurer** [comment]
@Trentonoliphant can you verify that there is a bld.bat in the conda.recipe?

**Comment by lidavidm** [comment]
Ah. The error is not that `bld.bat` doesn't exist, but that `bld.bat` ran `setup.py` which failed when it ran `coffee` - it couldn't find `coffee`. Is `coffee`/NodeJS in the path?

**Comment by Trentonoliphant** [comment]
I ran conda update conda-build and It said that version 1.7.0 was already installed.
Yes there is a bld.bat.

coffee/NodeJS is not in the path

**Comment by lidavidm** [comment]
@Trentonoliphant please run `npm -g coffee-script`. This will install CoffeeScript globally and it should then be on your path.

**Comment by Trentonoliphant** [comment]
it doesn't look like npm knows what to do with `-g coffee-script`, it gives examples of npm usage when it's run.

**Comment by lidavidm** [comment]
Ack, I'm sorry. `npm install -g coffee-script`.

**Comment by Trentonoliphant** [comment]
Still gives the same traceback, it doesn't look like coffee/NodeJS is on the path after running `npm install -g coffee-script`.

**Comment by lidavidm** [comment]
Hmm. You might have to edit the path then. Or you could try running from the "node command prompt" that should be in your start menu.

**Comment by Trentonoliphant** [comment]
Nothing changed when running from the node command prompt, and I'm not seeing any coffee folders that aren't coffee-script.

**Comment by lidavidm** [comment]
Hmm, then I guess you should modify your PATH.

Right click "My Computer" > Properties > Advanced > Environment Variables and edit path to add `; C:\Documents and Settings\user\Application data\npm; C:\Program Files\nodejs` (this will vary for Windows 7/8 - I think it is `C:\Users` instead of `C:\Documents and Settings` and on Windows 8 I don't recall how to get to the settings dialog).

Or just `set PATH=%PATH%;C:\Documents and Settings\...` in the command prompt.

**Comment by Trentonoliphant** [comment]
Updated the path to include `C:\Program Files\nodejs`,(`...appdata\npm` was already in it) and ran it again but had the same problem.

**Comment by lidavidm** [comment]
And the AppData\npm folder contains coffee, and echo %PATH% gives the
correct path? (Also note the path isn't updated unless you open a new
terminal.)

**Comment by Trentonoliphant** [comment]
I opened a new terminal and checked the path, it was correct.
In the appdata\npm folder there is a coffee file and a coffee.cmd file.
No change.

**Comment by lidavidm** [comment]
Hmm. That's odd. Can you run coffee in the terminal though?

**Comment by Trentonoliphant** [comment]
yes, I'm not sure what it does but it seems like it puts me in a sub terminal of sorts.

**Comment by lidavidm** [comment]
It puts you in the REPL (control D should exit it). It looks like
conda-build isn't inheriting the path, I'm not sure why though.

**Comment by lidavidm** [comment]
@Trentonoliphant Okay, I found the issue. On Windows `coffee` is a batch file. `setup.py` needs to call with `shell=True` for it to work. I have pushed a fix to master.

**Comment by Trentonoliphant** [comment]
That fixed it, I was able to build and install it successfully.
